services:
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/address-validator
    working_dir: /var/www/address-validator
  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/address-validator
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
