services:
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:1.27.4-alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
